sudo: required
services:
    - docker

before_install:
    - docker build -t percymamedy/docker-react -f Dockerfile.dev .

script:
    - docker run percymamedy/docker-react npm run test -- --coverage
